name = "cf-hono-app"
compatibility_date = "2024-09-02"
main = "src/index.ts"
minify = true
# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "KV"
# id = "13450004194144c38ef264d360dbc498"

# [[r2_buckets]]
# binding = "R2"
# bucket_name = "hono-r2-bucket"

 [[d1_databases]]
 binding = "DB"
 database_name = "hono-cf-db"
 database_id = "d49745da-cd6e-46f6-8a3b-7ddaf1951ffa"

# [ai]
# binding = "AI"