name = "cf-hono-app"

main = "src/index.ts"
compatibility_date = "2024-10-22"
minify = true
compatibility_flags = [ "nodejs_compat_v2" ]
[observability.logs]
enabled = true
# [vars]
# Public variables can be added here

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "13450004194144c38ef264d360dbc498"

# Secrets that should be set with `wrangler secret put`
# PINECONE_API_KEY
# COHERE_API_KEY
# GROQ_API_KEY
# DEEPGRAM_API_KEY


 [[r2_buckets]]
 binding = "R2"
 bucket_name = "hono-r2-bucket"

 [[d1_databases]]
 binding = "DB"
 database_name = "hono-cf-db"
 database_id = "d49745da-cd6e-46f6-8a3b-7ddaf1951ffa"

# [ai]
# binding = "AI"

[[workflows]]
name = "transcription-workflow"
binding = "TRANSCRIPTION_WORKFLOW"
class_name = "TranscriptionWorkflow"